services:
  ms-route.api:
    container_name: ms-route
    image: ms-route.api
    build:
      context: .
      dockerfile: src/ms-route.Api/Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - .env
    networks:
      - sg-services-network

  ms-route.tests:
    container_name: ms-route-tests
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /src
    volumes:
      - ./:/src
    command: dotnet test ./tests/ms-route.Tests/ --nologo
    profiles: [ "tests" ]
    networks:
      - sg-services-network

networks:
  sg-services-network:
    external: true
