syntax = "proto3";
option csharp_namespace = "ms_route.Api.Infrastructure.Grpc";
package route;

service RouteService {
  rpc CreateRoute (CreateRouteRequest) returns (CreateRouteResponse);
  rpc GetRoute (GetRouteRequest) returns (GetRouteResponse);
  rpc ListRoutes (ListRoutesRequest) returns (ListRoutesResponse);
  rpc UpdateRoute (UpdateRouteRequest) returns (UpdateRouteResponse);
  rpc DeleteRoute (DeleteRouteRequest) returns (DeleteRouteResponse);
  rpc GetCurrentRoute (GetCurrentRouteRequest) returns (GetCurrentRouteResponse);
  rpc GetStudentRoute (GetStudentRouteRequest) returns (GetStudentRouteResponse);
  rpc StartTrip (StartTripRequest) returns (StartTripResponse);
  rpc EndTrip (EndTripRequest) returns (EndTripResponse);
  rpc AssignStudentToRoute (AssignStudentToRouteRequest) returns (AssignStudentToRouteResponse);
  rpc AssignBusToRoute (AssignBusToRouteRequest) returns (AssignBusToRouteResponse);
}

message CreateRouteRequest {
  string campuse_id = 1;
  string name = 2;
  string target_sector = 3;
}

message CreateRouteResponse {
  string id = 1;
  string name = 2;
  string target_sector = 3;
  string status = 4;
}

message GetRouteRequest {
  string id = 1;
}

message GetRouteResponse {
  string id = 1;
  string name = 2;
  string target_sector = 3;
  string status = 4;
  string campuse_id = 5;
}

message ListRoutesRequest {}

message RouteListItem {
  string id = 1;
  string name = 2;
}

message ListRoutesResponse {
  repeated RouteListItem routes = 1;
}

message UpdateRouteRequest {
  string id = 1;
  string campuse_id = 2;
  string name = 3;
  string target_sector = 4;
}

message UpdateRouteResponse {
  string id = 1;
  string name = 2;
  string target_sector = 3;
  string status = 4;
}

message DeleteRouteRequest {
  string id = 1;
}

message DeleteRouteResponse {
  bool success = 1;
}

message GetCurrentRouteRequest {
  string driver_id = 1;
}

message GetCurrentRouteResponse {
  string id = 1;
  string name = 2;
  string campuse_id = 3;
  string target_sector = 4;
  string status = 5;
}

message GetStudentRouteRequest {
  string student_id = 1;
}

message GetStudentRouteResponse {
  string id = 1;
  string name = 2;
  string campuse_id = 3;
  string target_sector = 4;
  string status = 5;
}

message StartTripRequest {
  string route_id = 1;
  string bus_id = 2;
  string driver_id = 3;
}

message StartTripResponse {
  string id = 1;
  string bus_id = 2;
  string driver_id = 3;
  string status = 4;
}

message EndTripRequest {
  string trip_id = 1;
}

message EndTripResponse {
  string id = 1;
  string bus_id = 2;
  string driver_id = 3;
  string status = 4;
}

message AssignStudentToRouteRequest {
  string route_id = 1;
  string student_id = 2;
  string stop_id = 3;
}

message AssignStudentToRouteResponse {
  string id = 1;
  string route_id = 2;
  string student_id = 3;
  string stop_id = 4;
  string status = 5;
}

message AssignBusToRouteRequest {
  string route_id = 1;
  string bus_id = 2;
}

message AssignBusToRouteResponse {
  string id = 1;
  string route_id = 2;
  string bus_id = 3;
  string status = 4;
}
